<?php
/**
 * @file Provides VoIP Drupal functionality for the Claro project
 */

foreach (array('claro.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Implementation of hook_menu().
 */
function claro_menu() {
  $items['admin/voip/claro'] = array(
    'title' => 'SMS Broadcast',
    'description' => 'SMS Broadcast admin page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('claro_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function claro_admin_settings_form() {
  /*$form['claro_sms_footnote'] = array(
    '#type' => 'textfield',
    '#title' => t('SMS footnote'),
    '#description' => t('SMS footnote to apply at end of each SMS sent by the system'),
    '#default_value' => variable_get('claro_sms_footnote', ''),
  );*/

  $form['claro_sms_help'] = array(
    '#type' => 'textfield',
    '#title' => t('SMS help'),
    '#description' => t('Text SMS help message'),
    '#default_value' => variable_get('claro_sms_help', 'To subscribe to the list please text SUBSCRIBE. To Stop getting messages, text S. For help, text H.'),
  );

  $form['claro_sms_welcome'] = array(
    '#type' => 'textfield',
    '#title' => t('SMS welcome'),
    '#description' => t('Welcome SMS for text to be sent the first time a user subscribes to the service.'),
    '#default_value' => variable_get('claro_sms_welcome', 'Welcome to NannyVan App'),
  );

  return system_settings_form($form);
}
function claro_node_presave($node) {
  global $user;
  if($node->type == 'phone_number') {
    if(!$node->title) {
      $node->title = $node->field_phone_number['und'][0]['vnid'];
    }
    if($node->status == 0) {
      watchdog('claro', 'sending verification');
      //Send verification only for guest users
      $number = $node->field_phone_number['und'][0]['vnid'];
      $call = new VoipCall();
      $call->setDestNumber($number);
      $text = 'Reply Y to give permission to join the mobile list.';
      //@todo: use queue?
      voip_text($text, $call);
      //drupal_get_messages('status');
      drupal_set_message("SMS invitation has been sent to your number.");
    }
  }
}

//@todo: Map languages to destination numbers
function claro_number_to_lang($number){
  /*$languages = array(
    '+16177022395' => 'en',
  );
  return isset($languages[$number]) ? $languages[$number] : 'en';*/
  return 'en';
}

/**
 * Implementation of hook_form_alter()
 */
function claro_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'phone_number_node_form') {
    drupal_add_js(drupal_get_path('module', 'claro').'/claro.js');
    drupal_set_title(t('Subscribe to SMS announcements'));

    $form["options"]["#title"] = t("Send Invitation Option");
    $form["options"]["status"]["#title"] = t("Add to the list without sending invitation?");
    $form["options"]["promote"]["#type"] = "hidden";
    $form["options"]["sticky"]["#type"] = "hidden";
  }
  else if($form_id == 'broadcast_node_form') {
   //_d($form);
    drupal_set_title(t('Announcement creation'));
    drupal_add_js(drupal_get_path('module', 'claro').'/claro.js');
    $form['actions']['submit']['#value'] = t('Start');
    $form['actions']['preview']['#value'] = t('Test');

    $form['actions']['preview']['#submit'] = array('claro_broadcast_node_test');
    //so the $form_state['nid']  is available
    //$form['actions']['submit']['#submit'][]  = 'claro_broadcast_node_form_submit';
  }
  else if ($form_id == 'episode_node_form'){
    drupal_add_js(drupal_get_path('module', 'claro').'/claro.js');
  }
  return $form;
}

/*Send announcement to test number*/
function claro_broadcast_node_test($form, &$form_state) {
  $call = new VoipCall();
  $call->setDestNumber($form_state['values']['field_test_phone_number']['und'][0]['vnid']);
  $text = $form_state['values']['body']['und'][0]['value'];
  //@todo: use queue?
  voip_text($text, $call);
  drupal_set_message('SMS sent to test number '.$form_state['values']['field_test_phone_number']['und'][0]['vnid']);

  $form_state['rebuild'] = TRUE;
}





function claro_get_phone_number($phone_number) {
  $query = db_select('voipnumber', 'vn');
  $query->fields('vn');
  $query->condition('phone_number' , $phone_number);
  $query->leftJoin('field_data_field_phone_number', 'pn','pn.field_phone_number_vnid=vn.vnid');
  $query = $query->execute();
  $result = $query->fetchObject();
  if($result) {
    $phone_number = node_load($result->nid);
    return $phone_number;
  }
  return NULL;
}
/*
function _claro_get_phone_numbers() {
  $phone_numbers = array();
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'phone_number')
    ->propertyCondition('status', 1)
    ->addMetaData('account', user_load(1)); // Run the query as user 1.
  $result = $query->execute();
  if (isset($result['node'])) {
    $phone_number_nids = array_keys($result['node']);
    $phone_number_items = node_load_multiple($phone_number_nids);
    foreach ($phone_number_items as $node) {
      $phone_numbers[$node->field_phone_number['und'][0]['vnid']] = $node->field_phone_number['und'][0]['vnid'];
    }
  }
watchdog('debug', 'pn '.print_r($phone_numbers,true));
  return $phone_numbers;
}*/
function _d($obj) {
  print '<pre>';
  var_dump($obj);
  print '</pre>';
  die();
}
